// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBw0vjMAnLgX_M5mMFDLvSiTP7QqY5cWQ',
    appId: '1:1058854693075:web:860ad9af458285c31c0c26',
    messagingSenderId: '1058854693075',
    projectId: 'flashchat-13577',
    authDomain: 'flashchat-13577.firebaseapp.com',
    storageBucket: 'flashchat-13577.appspot.com',
    measurementId: 'G-7MM9JBFXXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSgTAlunsTRjI-i2WAF0KMChLIeYy9kWk',
    appId: '1:1058854693075:android:61b2dbf9d85818301c0c26',
    messagingSenderId: '1058854693075',
    projectId: 'flashchat-13577',
    storageBucket: 'flashchat-13577.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATWREeRKqwKVvRDdnAGDtrPfT8zCAPT2M',
    appId: '1:1058854693075:ios:c4d5c08d0d03a97d1c0c26',
    messagingSenderId: '1058854693075',
    projectId: 'flashchat-13577',
    storageBucket: 'flashchat-13577.appspot.com',
    iosClientId: '1058854693075-56soh38p0gu99v2b8t7c45cnv6ghb5as.apps.googleusercontent.com',
    iosBundleId: 'com.testing.flashchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATWREeRKqwKVvRDdnAGDtrPfT8zCAPT2M',
    appId: '1:1058854693075:ios:e0d12b6ce59321431c0c26',
    messagingSenderId: '1058854693075',
    projectId: 'flashchat-13577',
    storageBucket: 'flashchat-13577.appspot.com',
    iosClientId: '1058854693075-2j9q7vtg58s9e1p64qklal2psbtip9tc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashchat.RunnerTests',
  );
}
