# Uncomment the next line to define a global platform for your project
platform :ios, '16.6'

# Enable modular headers for all dependencies
use_modular_headers!

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
  ENV['COCOAPODS_DISABLE_STATS'] = 'true'

  project 'Runner', {
    'Debug' => :debug,
    'Profile' => :release,
    'Release' => :release,
  }
  # Pods for Runner

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
